### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by XXTelytrek** [RusheerPL/demGenerator#11]
jak kończe z tymi dem generator 1 itd to ak patrze tam gdzie mają być pliki ortho to jest sam zielony ekran help

**Comment by CrusheerPL** [comment]
podeślij plik z konfiguracją

**Comment by XXTelytrek** [comment]
cały dem generator ??? bo ja tera zrobiłem na innym lapku i są szare

**Comment by CrusheerPL** [comment]
plik z konfiguracją... niemniej jednak sprawdź w nim współrzędne bo zapewne je źle wyliczyłeś, zrób to jeszcze raz od nowa, zamykam w takim razie

**Comment by XXTelytrek** [comment]
wyliczyłem dobrze, a bo ja ominołem tą podmianke pod koniec poradnika 1 czy to na to wpływa? jak tak to wytłumacz jak to sie robi bo ja troche nie ogarniam
