### ISSUE TITLE
Do not use hardcoded workspace in generate scripts

### ISSUE THREAD

**Issue by LoogleCZ** [RusheerPL/demGenerator#6]
As of now, scripts have hardcoded config path (`demGenerator_config.txt`) and workspace folder (`demGen_data`). It would be nice to be able to configure where to load configuraiton and where to store intermediate results (if needed). Current values can be used as defaults

**Comment by CrusheerPL** [comment]
Got it: https://github.com/CrusheerPL/demgen/releases/tag/v1.0.0
