### ISSUE TITLE
Weird behaviour when generating heights (CZ)

### ISSUE THREAD

**Issue by LoogleCZ** [RusheerPL/demGenerator#7]
When generating heights for the map (country=CZ), script (mod2) tends to create download peaks.

![image](https://user-images.githubusercontent.com/13019504/72841478-c40a6d00-3c96-11ea-8ea9-0eb64b655942.png)

I would expect constant network usage when downloading heights data. Also consider bit refactor of mod2. In the script, "stupid" str.split is used to get data out of json. Thats one thing, another thing is, that in case when you will generate 4x4 map (my case), it will open ~4227136 connections just to get one number. Web protection services can detect this ammount of connections as an attack and will cause slow down for that user.

TODO:

- In [the documentation](http://ags.cuzk.cz/arcgis2/sdk/rest/index.html#/Image_Service/02ss00000021000000/) find way how to download bulk of datas
- Refactor mod2 to be able to download just one datafile with all necesary heights

Impact:

Because of this issue, this script hard to use for large maps in czech environment.

**Comment by LoogleCZ** [comment]
I think it will be better to download height data as image and do the transformation with that downloaded image. I think I've found API endpoint for downloading such image (further investigation needed)

https://ags.cuzk.cz/arcgis2/rest/services/dmr5g/ImageServer/exportImage?bbox=-904703.61%2C-1227416.66%2C-431605.61%2C-935124.6599999999&bboxSR=&size=4096%2C4096&imageSR=&time=&format=jpgpng&pixelType=F32&noData=&noDataInterpretation=esriNoDataMatchAny&interpolation=+RSP_BilinearInterpolation&compression=&compressionQuality=&bandIds=&mosaicRule=&renderingRule=&f=html

**Comment by CrusheerPL** [comment]
I am going to use the `getSamples` method (https://ags.cuzk.cz/arcgis2/rest/services/dmr5g/ImageServer/getSamples) instead of `identify`.
The `getSamples` method allows you to enter the coordinates of more than one point, if the `geometryType` parameter is set to `esriGeometryMultipoint`. As a result, the `mod2` execution time may be shorter.
More info: http://ags.cuzk.cz/arcgis2/sdk/rest/index.html#/Get_Samples/02ss000000ms000000/

**Comment by LoogleCZ** [comment]
Thanks, this would help (certainly this will shorten the execution time), but I'm still afraid that there will still be too much unnecessary amount of data.

But start with `GetSamples` method is a good approach of course, then I will try to use [`ExportImage`](http://ags.cuzk.cz/arcgis2/sdk/rest/index.html#/Export_Image/02ss00000075000000/) for processing area tile. (I think we don't need samples or identify because we want to sample continuous area). And processing images in python is not a problem at all

**Comment by CrusheerPL** [comment]
Unfortunately, I can't give so many points' coordinates in one query. In this video you can see why.
https://streamable.com/ojw5q
38 points in one query – OK.
39 and more – HTTP 404.
But always something.

**Comment by LoogleCZ** [comment]
Maybe internal response limit? From documentation:

> The number of sample locations in the response is based on the sampleDistance or sampleCount parameter and cannot exceed the limit of the image service (the default is 1000, which is an approximate limit).

But HTTP 404 is weird way how to indicate that limit is exceeded. I will try `ExportImage` now and let you kow my results

**Comment by LoogleCZ** [comment]
I've managed to export image based on lat/long coordinates (spatial reference 4326) and resulting image is in Krovak projection (spatial reference 5514). But then I don't know how to exactly use that image (must figure out later).

My idea is:

1. generate array of points on which we want to know heights (in WGS84, because I know how to do in this coordinate system - approx.)
2. Download image (min and max values from previous step, in WGS84 - SRS 4326) in Krovak projection (SRS 5514)
3. **Somehow address the image as 2D image array with S-JTSK coordinates**. Shifting along axis X in WGS84 != shifting along X in S-JTSK. But maybe simple transformation from WGS84 will be enough to get index into the image. I'm too tired for this math now.
4. Use sampled values as height values.

Resource:

[Get image - input bounding box in WGS84, output image in S-JTSK](https://ags.cuzk.cz/arcgis2/rest/services/dmr5g/ImageServer/exportImage?bbox=12%2C%2049%2C%2019%2C%2050&bboxSR=4326&size=512%2C512&imageSR=5514&time=&format=jpgpng&pixelType=U32&noData=&noDataInterpretation=esriNoDataMatchAny&interpolation=%20RSP_BilinearInterpolation&compression=&compressionQuality=&bandIds=&mosaicRule=&renderingRule=&f=html&fbclid=IwAR1jRxBdPHHvjFXEkfGFASuE_fpAQrCEtSJotxUOjVhRc66NnOUOLLTZzjU)

**Comment by CrusheerPL** [comment]
In spite of all, new version of this script seems to work fine. (2048 x 2048) m terrain in <10 minutes, without the weird behaviour mentioned in the 1st post.
<img src="https://abload.de/img/442wk3a.png" />
Maybe your idea would be good, but let's see how the new version will work :)
New version: https://github.com/RusheerPL/demGenerator/commit/44fcaf0a8f43614ac67bdd35ea17e350ea7476fd

**Comment by LoogleCZ** [comment]
Great - I will try to do it my way and I will use your solution as reference.
